#!/usr/bin/env python3
"""Generate content/topics/ from data/paper-topics.yaml.

FULLY GENERATED -- do not hand-edit content/topics/. Titles and descriptions both
come from the topics file; rerun this after editing it.

Writes:
  content/topics/_index.md          the taxonomy list page, with a cascade that makes
                                    every term page use the `citation` view
  content/topics/<slug>/_index.md   one per topic: title = name, body = scope

The cascade matters. Without it, term pages fall back to the theme's `card` view,
which renders each paper as an image card showing a read time and using the page
body as an excerpt -- so papers with a "previously circulated as" note led with
that instead of anything useful. `citation` matches /research/.
"""
import os, re, sys

TOPICS_FILE = "data/paper-topics.yaml"
OUT = "content/topics"

def slugify(name):
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")

def load():
    text = open(TOPICS_FILE, encoding="utf-8").read()
    head = text.partition("\npapers:")[0]
    topics = []
    for code, block in re.findall(r"^  (\w+):\n((?:    .*\n)+)", head, re.M):
        name = re.search(r"^    name:\s*(.+?)\s*$", block, re.M)
        scope = re.search(r"^    scope:\s*(.+?)\s*(?:#.*)?$", block, re.M)
        if not name:
            continue
        topics.append((code,
                       name.group(1).strip().strip("'\""),
                       (scope.group(1).strip().strip("'\"") if scope else "")))
    return topics

if __name__ == "__main__":
    topics = load()
    if not topics:
        sys.exit(f"no topics parsed from {TOPICS_FILE}")
    os.makedirs(OUT, exist_ok=True)

    open(os.path.join(OUT, "_index.md"), "w", encoding="utf-8").write(
        "---\n"
        "title: Research topics\n"
        "# GENERATED by scripts/gen_topic_pages.py -- edit data/paper-topics.yaml instead.\n"
        "# The cascade applies to every term page below: use the same `citation` view as\n"
        "# /research/, and drop the card view's date, read time and body excerpt.\n"
        "cascade:\n"
        "  view: citation\n"
        "  show_date: false\n"
        "  show_read_time: false\n"
        "  show_read_more: false\n"
        "---\n\n"
        "Papers grouped by research theme. Many appear under more than one.\n"
    )

    for code, name, scope in topics:
        d = os.path.join(OUT, slugify(name))
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, "_index.md"), "w", encoding="utf-8").write(
            "---\n"
            f'title: "{name}"\n'
            "# GENERATED by scripts/gen_topic_pages.py -- edit data/paper-topics.yaml instead.\n"
            "---\n\n"
            + (scope + "\n" if scope else "")
        )
    print(f"wrote {len(topics)} topic pages to {OUT}/")
